main:
  version: '0.1.3.0'
  author: 'intervision'
  authorlink: 'https://github.com/intervisionlord'
  icon: '../imgs/SSE_Icon.ico'

plugins: pyqt5

params:
  - windows-disable-console
  - follow-imports
  - onefile
  - standalone
  - remove-output
  - windows-product-name="Stationeers Save Editor"
  - windows-company-name="TWR"
  - windows-product-version
  - windows-file-description="Save editor for Stationeers game"

files:
  - imgs/save_icon_16.ico
  - imgs/SSE_Icon.ico