main:
  version: '0.1.2.1'
  author: 'intervision'
  authorlink: 'https://github.com/intervisionlord'
  icon: '../imgs/SSE_Icon.ico'

plugins: pyqt5

params:
  - windows-disable-console
  - follow-imports
  - onefile
  - standalone
  - remove-output

files:
  - imgs/save_icon_48.png
  - imgs/SSE_Icon.ico